//
// Copyright (c) Sojournercntl 2016/17. All rights reserved.  
// See LICENSE file in the project root for full license information.
//
package org.sojournercntl.solarflare.userinterface;

import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URI;
import org.sojournercntl.image.Imagehelper;

import javax.swing.UIManager;
import java.awt.Color;
import net.miginfocom.swing.MigLayout;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import java.awt.Font;
import javax.swing.JTextPane;
import javax.swing.JSeparator;

/**
 * SolarAbout Frame
 * @author sojournercntl
 * @version 1.0
 */
@SuppressWarnings("serial")
public class SolarAbout extends javax.swing.JFrame {
    
    /** Creates new form AboutJFrame */
    public SolarAbout() {
    	setIconImage(null);
    	getContentPane().setBackground(UIManager.getColor("Button.highlight"));
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);
        getContentPane().setLayout(new MigLayout("", "[grow][grow]", "[][][249px,grow][][][][35px]"));
        
        JLabel lblSolarFlare = new JLabel("Solar Flare");
        lblSolarFlare.setFont(new Font("Dialog", Font.BOLD, 18));
        getContentPane().add(lblSolarFlare, "cell 0 0 2 1,alignx center");
        lblSolarFlare.setHorizontalAlignment(SwingConstants.CENTER);
        lblSolarFlare.setForeground(Color.WHITE);
        
        JLabel lblNewLabel = new JLabel("");
        getContentPane().add(lblNewLabel, "cell 0 1 2 1,alignx center");
        
			//new ImageIcon("C:\\SojournerDevelopment\\Projecte\\SolarFlare\\ResFiles\\SolarFlareLogo.png")
        	try{
        		BufferedImage image=ImageIO.read(new File("ResFiles\\SolarFlareLogo.png"));
                BufferedImage resizedImage=Imagehelper.resize(image,100,100);
                lblNewLabel.setIcon(new ImageIcon(resizedImage));
        	}catch(Exception ex){
        		ex.printStackTrace();
        	}
        
        JTextPane txtpnSolarFlareIs = new JTextPane();
        txtpnSolarFlareIs.setBackground(Color.DARK_GRAY);
        //txtpnSolarFlareIs.setBackground(new Color(0, 0, 0));
        txtpnSolarFlareIs.setText("Solar Flare is a software developed by Sojournercntl.\r\n\r\nSolar Flare Network Scanner is a tool to scan your\r\nnetwork for devices and objects communicating in\r\nit. You should only use the tool to administrate your\r\nown network. It has been developed for educational\r\npurposes only!\r\n\r\nIf you need support using the software feel free to\r\ncontact me via the Contact Form on my Website.\r\nYou are not permitted to modify the sourcecode in\r\nany way. Do not share your API Key under any\r\ncircumstances!");
        txtpnSolarFlareIs.setEditable(false);
        getContentPane().add(txtpnSolarFlareIs, "flowy,cell 0 2 2 1,grow");
        
        JLabel lblYourApiKey = new JLabel("Your api key: //Currently unavailable//");
        getContentPane().add(lblYourApiKey, "cell 0 3 2 1");
        
        JSeparator separator = new JSeparator();
        separator.setBackground(new Color(255, 255, 255));
        separator.setForeground(new Color(255, 69, 0));
        getContentPane().add(separator, "cell 0 5 2 1,growx");


        jLabel4 = new javax.swing.JLabel();
        getContentPane().add(jLabel4, "flowx,cell 0 6");
        
                jLabel4.setForeground(new Color(255, 99, 71));
                jLabel4.setText("sojournercntl");
                jButton1 = new javax.swing.JButton();
                //jButton1.setBackground(new Color(0, 0, 0));
                
                        jButton1.setText("Close About\r\n");
                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(jButton1, "cell 1 6,alignx right,growy");
                        
                        JLabel lblSolarFlareIs = new JLabel("2016/17 all rights reserved!");
                        getContentPane().add(lblSolarFlareIs, "cell 0 6");
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel4MouseClicked(evt);
                    }
                });
                
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {        
            Desktop.getDesktop().browse(new URI("http://sojournercntl.comxa.com/"));
        }
        catch (Exception e) {
            e.getStackTrace();
        }        
    }//GEN-LAST:event_jLabel4MouseClicked
       
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	try {
    		UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
    	} catch (Throwable e) {
    		e.printStackTrace();
    	}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolarAbout().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
}
